### PR TITLE
Small Refactor and Fix Related to Order Creation

### PR DESCRIPTION
**Pull request by sabondano**
- fixed 'continue shopping' and 'dashboard' links on orders index view
- small refactoring for #create action in OrdersController that reads a little better than before

### CODE REVIEW

**Comment by michael-reeves** [comment]
Looks good to me.

**Comment by mdorrance** [comment]
Looks good to me and Sam.

**Comment by sabondano** [comment]
Please merge.

**Comment by imwithsam** [comment]
Lookin' good! Merging.

**Pull request merged**
